name: Lint Code

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      
      - name: Run Linter
        run: |
          find . -name "*.py" -exec flake8 {} +
          echo "Linted all the Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Install JSHint
        run: npm install jshint --global
      
      - name: Run Linter
        run: |
          find . -name "*.js" -exec jshint {} +
          echo "Linted all the JavaScript files successfully"
